spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/advancedPmTasks
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changeLog.xml
server:
  port: 8080